name: e_commerce_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.2

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  http: ^1.2.2
  json_serializable: ^6.11.0
  lints: ^6.0.0
  test: ^1.25.6
